apiVersion: apps/v1 
kind: Deployment
metadata:
  name: regapp-deployment
  labels: 
     app: regapp
 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp
 
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: 869935099473.dkr.ecr.ap-south-1.amazonaws.com/docker-image:latest         # after running the workflow for first time
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
